// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EquipmentManager.proto

#ifndef PROTOBUF_EquipmentManager_2eproto__INCLUDED
#define PROTOBUF_EquipmentManager_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_EquipmentManager_2eproto();
void protobuf_AssignDesc_EquipmentManager_2eproto();
void protobuf_ShutdownFile_EquipmentManager_2eproto();

class Equipment;
class EquipmentCache;
class Equipment_RowingMachine;
class Equipment_Treadmill;

// ===================================================================

class Equipment_Treadmill : public ::google::protobuf::Message {
 public:
  Equipment_Treadmill();
  virtual ~Equipment_Treadmill();

  Equipment_Treadmill(const Equipment_Treadmill& from);

  inline Equipment_Treadmill& operator=(const Equipment_Treadmill& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Equipment_Treadmill& default_instance();

  void Swap(Equipment_Treadmill* other);

  // implements Message ----------------------------------------------

  inline Equipment_Treadmill* New() const { return New(NULL); }

  Equipment_Treadmill* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Equipment_Treadmill& from);
  void MergeFrom(const Equipment_Treadmill& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Equipment_Treadmill* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float distance = 1;
  void clear_distance();
  static const int kDistanceFieldNumber = 1;
  float distance() const;
  void set_distance(float value);

  // optional float avgSpeed = 2;
  void clear_avgspeed();
  static const int kAvgSpeedFieldNumber = 2;
  float avgspeed() const;
  void set_avgspeed(float value);

  // @@protoc_insertion_point(class_scope:proto.Equipment.Treadmill)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float distance_;
  float avgspeed_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EquipmentManager_2eproto();
  friend void protobuf_AssignDesc_EquipmentManager_2eproto();
  friend void protobuf_ShutdownFile_EquipmentManager_2eproto();

  void InitAsDefaultInstance();
  static Equipment_Treadmill* default_instance_;
};
// -------------------------------------------------------------------

class Equipment_RowingMachine : public ::google::protobuf::Message {
 public:
  Equipment_RowingMachine();
  virtual ~Equipment_RowingMachine();

  Equipment_RowingMachine(const Equipment_RowingMachine& from);

  inline Equipment_RowingMachine& operator=(const Equipment_RowingMachine& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Equipment_RowingMachine& default_instance();

  void Swap(Equipment_RowingMachine* other);

  // implements Message ----------------------------------------------

  inline Equipment_RowingMachine* New() const { return New(NULL); }

  Equipment_RowingMachine* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Equipment_RowingMachine& from);
  void MergeFrom(const Equipment_RowingMachine& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Equipment_RowingMachine* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float duration = 1;
  void clear_duration();
  static const int kDurationFieldNumber = 1;
  float duration() const;
  void set_duration(float value);

  // optional float repsPerMin = 2;
  void clear_repspermin();
  static const int kRepsPerMinFieldNumber = 2;
  float repspermin() const;
  void set_repspermin(float value);

  // @@protoc_insertion_point(class_scope:proto.Equipment.RowingMachine)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float duration_;
  float repspermin_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EquipmentManager_2eproto();
  friend void protobuf_AssignDesc_EquipmentManager_2eproto();
  friend void protobuf_ShutdownFile_EquipmentManager_2eproto();

  void InitAsDefaultInstance();
  static Equipment_RowingMachine* default_instance_;
};
// -------------------------------------------------------------------

class Equipment : public ::google::protobuf::Message {
 public:
  Equipment();
  virtual ~Equipment();

  Equipment(const Equipment& from);

  inline Equipment& operator=(const Equipment& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Equipment& default_instance();

  enum EquipmentTypeCase {
    kTreadmill = 4,
    kRowingMachine = 5,
    EQUIPMENTTYPE_NOT_SET = 0,
  };

  void Swap(Equipment* other);

  // implements Message ----------------------------------------------

  inline Equipment* New() const { return New(NULL); }

  Equipment* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Equipment& from);
  void MergeFrom(const Equipment& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Equipment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Equipment_Treadmill Treadmill;
  typedef Equipment_RowingMachine RowingMachine;

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string date = 2;
  void clear_date();
  static const int kDateFieldNumber = 2;
  const ::std::string& date() const;
  void set_date(const ::std::string& value);
  void set_date(const char* value);
  void set_date(const char* value, size_t size);
  ::std::string* mutable_date();
  ::std::string* release_date();
  void set_allocated_date(::std::string* date);

  // optional int32 id = 3;
  void clear_id();
  static const int kIdFieldNumber = 3;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // optional .proto.Equipment.Treadmill treadmill = 4;
  bool has_treadmill() const;
  void clear_treadmill();
  static const int kTreadmillFieldNumber = 4;
  const ::proto::Equipment_Treadmill& treadmill() const;
  ::proto::Equipment_Treadmill* mutable_treadmill();
  ::proto::Equipment_Treadmill* release_treadmill();
  void set_allocated_treadmill(::proto::Equipment_Treadmill* treadmill);

  // optional .proto.Equipment.RowingMachine rowingMachine = 5;
  bool has_rowingmachine() const;
  void clear_rowingmachine();
  static const int kRowingMachineFieldNumber = 5;
  const ::proto::Equipment_RowingMachine& rowingmachine() const;
  ::proto::Equipment_RowingMachine* mutable_rowingmachine();
  ::proto::Equipment_RowingMachine* release_rowingmachine();
  void set_allocated_rowingmachine(::proto::Equipment_RowingMachine* rowingmachine);

  EquipmentTypeCase EquipmentType_case() const;
  // @@protoc_insertion_point(class_scope:proto.Equipment)
 private:
  inline void set_has_treadmill();
  inline void set_has_rowingmachine();

  inline bool has_EquipmentType() const;
  void clear_EquipmentType();
  inline void clear_has_EquipmentType();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr date_;
  ::google::protobuf::int32 id_;
  union EquipmentTypeUnion {
    EquipmentTypeUnion() {}
    ::proto::Equipment_Treadmill* treadmill_;
    ::proto::Equipment_RowingMachine* rowingmachine_;
  } EquipmentType_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_EquipmentManager_2eproto();
  friend void protobuf_AssignDesc_EquipmentManager_2eproto();
  friend void protobuf_ShutdownFile_EquipmentManager_2eproto();

  void InitAsDefaultInstance();
  static Equipment* default_instance_;
};
// -------------------------------------------------------------------

class EquipmentCache : public ::google::protobuf::Message {
 public:
  EquipmentCache();
  virtual ~EquipmentCache();

  EquipmentCache(const EquipmentCache& from);

  inline EquipmentCache& operator=(const EquipmentCache& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EquipmentCache& default_instance();

  void Swap(EquipmentCache* other);

  // implements Message ----------------------------------------------

  inline EquipmentCache* New() const { return New(NULL); }

  EquipmentCache* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EquipmentCache& from);
  void MergeFrom(const EquipmentCache& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EquipmentCache* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.Equipment equipment = 1;
  int equipment_size() const;
  void clear_equipment();
  static const int kEquipmentFieldNumber = 1;
  const ::proto::Equipment& equipment(int index) const;
  ::proto::Equipment* mutable_equipment(int index);
  ::proto::Equipment* add_equipment();
  ::google::protobuf::RepeatedPtrField< ::proto::Equipment >*
      mutable_equipment();
  const ::google::protobuf::RepeatedPtrField< ::proto::Equipment >&
      equipment() const;

  // @@protoc_insertion_point(class_scope:proto.EquipmentCache)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::proto::Equipment > equipment_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EquipmentManager_2eproto();
  friend void protobuf_AssignDesc_EquipmentManager_2eproto();
  friend void protobuf_ShutdownFile_EquipmentManager_2eproto();

  void InitAsDefaultInstance();
  static EquipmentCache* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Equipment_Treadmill

// optional float distance = 1;
inline void Equipment_Treadmill::clear_distance() {
  distance_ = 0;
}
inline float Equipment_Treadmill::distance() const {
  // @@protoc_insertion_point(field_get:proto.Equipment.Treadmill.distance)
  return distance_;
}
inline void Equipment_Treadmill::set_distance(float value) {
  
  distance_ = value;
  // @@protoc_insertion_point(field_set:proto.Equipment.Treadmill.distance)
}

// optional float avgSpeed = 2;
inline void Equipment_Treadmill::clear_avgspeed() {
  avgspeed_ = 0;
}
inline float Equipment_Treadmill::avgspeed() const {
  // @@protoc_insertion_point(field_get:proto.Equipment.Treadmill.avgSpeed)
  return avgspeed_;
}
inline void Equipment_Treadmill::set_avgspeed(float value) {
  
  avgspeed_ = value;
  // @@protoc_insertion_point(field_set:proto.Equipment.Treadmill.avgSpeed)
}

// -------------------------------------------------------------------

// Equipment_RowingMachine

// optional float duration = 1;
inline void Equipment_RowingMachine::clear_duration() {
  duration_ = 0;
}
inline float Equipment_RowingMachine::duration() const {
  // @@protoc_insertion_point(field_get:proto.Equipment.RowingMachine.duration)
  return duration_;
}
inline void Equipment_RowingMachine::set_duration(float value) {
  
  duration_ = value;
  // @@protoc_insertion_point(field_set:proto.Equipment.RowingMachine.duration)
}

// optional float repsPerMin = 2;
inline void Equipment_RowingMachine::clear_repspermin() {
  repspermin_ = 0;
}
inline float Equipment_RowingMachine::repspermin() const {
  // @@protoc_insertion_point(field_get:proto.Equipment.RowingMachine.repsPerMin)
  return repspermin_;
}
inline void Equipment_RowingMachine::set_repspermin(float value) {
  
  repspermin_ = value;
  // @@protoc_insertion_point(field_set:proto.Equipment.RowingMachine.repsPerMin)
}

// -------------------------------------------------------------------

// Equipment

// optional string name = 1;
inline void Equipment::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Equipment::name() const {
  // @@protoc_insertion_point(field_get:proto.Equipment.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Equipment::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.Equipment.name)
}
inline void Equipment::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Equipment.name)
}
inline void Equipment::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Equipment.name)
}
inline ::std::string* Equipment::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:proto.Equipment.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Equipment::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Equipment::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:proto.Equipment.name)
}

// optional string date = 2;
inline void Equipment::clear_date() {
  date_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Equipment::date() const {
  // @@protoc_insertion_point(field_get:proto.Equipment.date)
  return date_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Equipment::set_date(const ::std::string& value) {
  
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.Equipment.date)
}
inline void Equipment::set_date(const char* value) {
  
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Equipment.date)
}
inline void Equipment::set_date(const char* value, size_t size) {
  
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Equipment.date)
}
inline ::std::string* Equipment::mutable_date() {
  
  // @@protoc_insertion_point(field_mutable:proto.Equipment.date)
  return date_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Equipment::release_date() {
  
  return date_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Equipment::set_allocated_date(::std::string* date) {
  if (date != NULL) {
    
  } else {
    
  }
  date_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), date);
  // @@protoc_insertion_point(field_set_allocated:proto.Equipment.date)
}

// optional int32 id = 3;
inline void Equipment::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 Equipment::id() const {
  // @@protoc_insertion_point(field_get:proto.Equipment.id)
  return id_;
}
inline void Equipment::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:proto.Equipment.id)
}

// optional .proto.Equipment.Treadmill treadmill = 4;
inline bool Equipment::has_treadmill() const {
  return EquipmentType_case() == kTreadmill;
}
inline void Equipment::set_has_treadmill() {
  _oneof_case_[0] = kTreadmill;
}
inline void Equipment::clear_treadmill() {
  if (has_treadmill()) {
    delete EquipmentType_.treadmill_;
    clear_has_EquipmentType();
  }
}
inline  const ::proto::Equipment_Treadmill& Equipment::treadmill() const {
  // @@protoc_insertion_point(field_get:proto.Equipment.treadmill)
  return has_treadmill()
      ? *EquipmentType_.treadmill_
      : ::proto::Equipment_Treadmill::default_instance();
}
inline ::proto::Equipment_Treadmill* Equipment::mutable_treadmill() {
  if (!has_treadmill()) {
    clear_EquipmentType();
    set_has_treadmill();
    EquipmentType_.treadmill_ = new ::proto::Equipment_Treadmill;
  }
  // @@protoc_insertion_point(field_mutable:proto.Equipment.treadmill)
  return EquipmentType_.treadmill_;
}
inline ::proto::Equipment_Treadmill* Equipment::release_treadmill() {
  if (has_treadmill()) {
    clear_has_EquipmentType();
    ::proto::Equipment_Treadmill* temp = EquipmentType_.treadmill_;
    EquipmentType_.treadmill_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Equipment::set_allocated_treadmill(::proto::Equipment_Treadmill* treadmill) {
  clear_EquipmentType();
  if (treadmill) {
    set_has_treadmill();
    EquipmentType_.treadmill_ = treadmill;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Equipment.treadmill)
}

// optional .proto.Equipment.RowingMachine rowingMachine = 5;
inline bool Equipment::has_rowingmachine() const {
  return EquipmentType_case() == kRowingMachine;
}
inline void Equipment::set_has_rowingmachine() {
  _oneof_case_[0] = kRowingMachine;
}
inline void Equipment::clear_rowingmachine() {
  if (has_rowingmachine()) {
    delete EquipmentType_.rowingmachine_;
    clear_has_EquipmentType();
  }
}
inline  const ::proto::Equipment_RowingMachine& Equipment::rowingmachine() const {
  // @@protoc_insertion_point(field_get:proto.Equipment.rowingMachine)
  return has_rowingmachine()
      ? *EquipmentType_.rowingmachine_
      : ::proto::Equipment_RowingMachine::default_instance();
}
inline ::proto::Equipment_RowingMachine* Equipment::mutable_rowingmachine() {
  if (!has_rowingmachine()) {
    clear_EquipmentType();
    set_has_rowingmachine();
    EquipmentType_.rowingmachine_ = new ::proto::Equipment_RowingMachine;
  }
  // @@protoc_insertion_point(field_mutable:proto.Equipment.rowingMachine)
  return EquipmentType_.rowingmachine_;
}
inline ::proto::Equipment_RowingMachine* Equipment::release_rowingmachine() {
  if (has_rowingmachine()) {
    clear_has_EquipmentType();
    ::proto::Equipment_RowingMachine* temp = EquipmentType_.rowingmachine_;
    EquipmentType_.rowingmachine_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Equipment::set_allocated_rowingmachine(::proto::Equipment_RowingMachine* rowingmachine) {
  clear_EquipmentType();
  if (rowingmachine) {
    set_has_rowingmachine();
    EquipmentType_.rowingmachine_ = rowingmachine;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Equipment.rowingMachine)
}

inline bool Equipment::has_EquipmentType() const {
  return EquipmentType_case() != EQUIPMENTTYPE_NOT_SET;
}
inline void Equipment::clear_has_EquipmentType() {
  _oneof_case_[0] = EQUIPMENTTYPE_NOT_SET;
}
inline Equipment::EquipmentTypeCase Equipment::EquipmentType_case() const {
  return Equipment::EquipmentTypeCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// EquipmentCache

// repeated .proto.Equipment equipment = 1;
inline int EquipmentCache::equipment_size() const {
  return equipment_.size();
}
inline void EquipmentCache::clear_equipment() {
  equipment_.Clear();
}
inline const ::proto::Equipment& EquipmentCache::equipment(int index) const {
  // @@protoc_insertion_point(field_get:proto.EquipmentCache.equipment)
  return equipment_.Get(index);
}
inline ::proto::Equipment* EquipmentCache::mutable_equipment(int index) {
  // @@protoc_insertion_point(field_mutable:proto.EquipmentCache.equipment)
  return equipment_.Mutable(index);
}
inline ::proto::Equipment* EquipmentCache::add_equipment() {
  // @@protoc_insertion_point(field_add:proto.EquipmentCache.equipment)
  return equipment_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto::Equipment >*
EquipmentCache::mutable_equipment() {
  // @@protoc_insertion_point(field_mutable_list:proto.EquipmentCache.equipment)
  return &equipment_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::Equipment >&
EquipmentCache::equipment() const {
  // @@protoc_insertion_point(field_list:proto.EquipmentCache.equipment)
  return equipment_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_EquipmentManager_2eproto__INCLUDED
