// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EquipmentManager.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "EquipmentManager.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Treadmill_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Treadmill_reflection_ = NULL;
const ::google::protobuf::Descriptor* RowingMachine_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RowingMachine_reflection_ = NULL;
const ::google::protobuf::Descriptor* Equipment_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Equipment_reflection_ = NULL;
struct EquipmentOneofInstance {
  const ::Treadmill* treadmill_;
  const ::RowingMachine* rowingmachine_;
}* Equipment_default_oneof_instance_ = NULL;
const ::google::protobuf::Descriptor* EquipmentCache_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  EquipmentCache_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_EquipmentManager_2eproto() {
  protobuf_AddDesc_EquipmentManager_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "EquipmentManager.proto");
  GOOGLE_CHECK(file != NULL);
  Treadmill_descriptor_ = file->message_type(0);
  static const int Treadmill_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Treadmill, distance_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Treadmill, avgspeed_),
  };
  Treadmill_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Treadmill_descriptor_,
      Treadmill::default_instance_,
      Treadmill_offsets_,
      -1,
      -1,
      -1,
      sizeof(Treadmill),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Treadmill, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Treadmill, _is_default_instance_));
  RowingMachine_descriptor_ = file->message_type(1);
  static const int RowingMachine_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RowingMachine, duration_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RowingMachine, repspermin_),
  };
  RowingMachine_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RowingMachine_descriptor_,
      RowingMachine::default_instance_,
      RowingMachine_offsets_,
      -1,
      -1,
      -1,
      sizeof(RowingMachine),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RowingMachine, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RowingMachine, _is_default_instance_));
  Equipment_descriptor_ = file->message_type(2);
  static const int Equipment_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Equipment, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Equipment, date_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Equipment_default_oneof_instance_, treadmill_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Equipment_default_oneof_instance_, rowingmachine_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Equipment, EquipmentType_),
  };
  Equipment_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Equipment_descriptor_,
      Equipment::default_instance_,
      Equipment_offsets_,
      -1,
      -1,
      -1,
      Equipment_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Equipment, _oneof_case_[0]),
      sizeof(Equipment),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Equipment, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Equipment, _is_default_instance_));
  EquipmentCache_descriptor_ = file->message_type(3);
  static const int EquipmentCache_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EquipmentCache, equipment_),
  };
  EquipmentCache_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      EquipmentCache_descriptor_,
      EquipmentCache::default_instance_,
      EquipmentCache_offsets_,
      -1,
      -1,
      -1,
      sizeof(EquipmentCache),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EquipmentCache, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EquipmentCache, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_EquipmentManager_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Treadmill_descriptor_, &Treadmill::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RowingMachine_descriptor_, &RowingMachine::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Equipment_descriptor_, &Equipment::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      EquipmentCache_descriptor_, &EquipmentCache::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_EquipmentManager_2eproto() {
  delete Treadmill::default_instance_;
  delete Treadmill_reflection_;
  delete RowingMachine::default_instance_;
  delete RowingMachine_reflection_;
  delete Equipment::default_instance_;
  delete Equipment_default_oneof_instance_;
  delete Equipment_reflection_;
  delete EquipmentCache::default_instance_;
  delete EquipmentCache_reflection_;
}

void protobuf_AddDesc_EquipmentManager_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026EquipmentManager.proto\"/\n\tTreadmill\022\020\n"
    "\010distance\030\001 \001(\002\022\020\n\010avgSpeed\030\002 \001(\002\"5\n\rRow"
    "ingMachine\022\020\n\010duration\030\001 \001(\002\022\022\n\nrepsPerM"
    "in\030\002 \001(\002\"\202\001\n\tEquipment\022\014\n\004name\030\001 \001(\t\022\014\n\004"
    "date\030\002 \001(\t\022\037\n\ttreadmill\030\004 \001(\0132\n.Treadmil"
    "lH\000\022\'\n\rrowingMachine\030\005 \001(\0132\016.RowingMachi"
    "neH\000B\017\n\rEquipmentType\"/\n\016EquipmentCache\022"
    "\035\n\tequipment\030\001 \003(\0132\n.Equipmentb\006proto3", 318);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "EquipmentManager.proto", &protobuf_RegisterTypes);
  Treadmill::default_instance_ = new Treadmill();
  RowingMachine::default_instance_ = new RowingMachine();
  Equipment::default_instance_ = new Equipment();
  Equipment_default_oneof_instance_ = new EquipmentOneofInstance();
  EquipmentCache::default_instance_ = new EquipmentCache();
  Treadmill::default_instance_->InitAsDefaultInstance();
  RowingMachine::default_instance_->InitAsDefaultInstance();
  Equipment::default_instance_->InitAsDefaultInstance();
  EquipmentCache::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_EquipmentManager_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_EquipmentManager_2eproto {
  StaticDescriptorInitializer_EquipmentManager_2eproto() {
    protobuf_AddDesc_EquipmentManager_2eproto();
  }
} static_descriptor_initializer_EquipmentManager_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int Treadmill::kDistanceFieldNumber;
const int Treadmill::kAvgSpeedFieldNumber;
#endif  // !_MSC_VER

Treadmill::Treadmill()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Treadmill)
}

void Treadmill::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Treadmill::Treadmill(const Treadmill& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Treadmill)
}

void Treadmill::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  distance_ = 0;
  avgspeed_ = 0;
}

Treadmill::~Treadmill() {
  // @@protoc_insertion_point(destructor:Treadmill)
  SharedDtor();
}

void Treadmill::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Treadmill::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Treadmill::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Treadmill_descriptor_;
}

const Treadmill& Treadmill::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_EquipmentManager_2eproto();
  return *default_instance_;
}

Treadmill* Treadmill::default_instance_ = NULL;

Treadmill* Treadmill::New(::google::protobuf::Arena* arena) const {
  Treadmill* n = new Treadmill;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Treadmill::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Treadmill*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(distance_, avgspeed_);

#undef ZR_HELPER_
#undef ZR_

}

bool Treadmill::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Treadmill)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float distance = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &distance_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_avgSpeed;
        break;
      }

      // optional float avgSpeed = 2;
      case 2: {
        if (tag == 21) {
         parse_avgSpeed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &avgspeed_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Treadmill)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Treadmill)
  return false;
#undef DO_
}

void Treadmill::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Treadmill)
  // optional float distance = 1;
  if (this->distance() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->distance(), output);
  }

  // optional float avgSpeed = 2;
  if (this->avgspeed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->avgspeed(), output);
  }

  // @@protoc_insertion_point(serialize_end:Treadmill)
}

::google::protobuf::uint8* Treadmill::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Treadmill)
  // optional float distance = 1;
  if (this->distance() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->distance(), target);
  }

  // optional float avgSpeed = 2;
  if (this->avgspeed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->avgspeed(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Treadmill)
  return target;
}

int Treadmill::ByteSize() const {
  int total_size = 0;

  // optional float distance = 1;
  if (this->distance() != 0) {
    total_size += 1 + 4;
  }

  // optional float avgSpeed = 2;
  if (this->avgspeed() != 0) {
    total_size += 1 + 4;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Treadmill::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Treadmill* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Treadmill>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Treadmill::MergeFrom(const Treadmill& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.distance() != 0) {
    set_distance(from.distance());
  }
  if (from.avgspeed() != 0) {
    set_avgspeed(from.avgspeed());
  }
}

void Treadmill::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Treadmill::CopyFrom(const Treadmill& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Treadmill::IsInitialized() const {

  return true;
}

void Treadmill::Swap(Treadmill* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Treadmill::InternalSwap(Treadmill* other) {
  std::swap(distance_, other->distance_);
  std::swap(avgspeed_, other->avgspeed_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Treadmill::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Treadmill_descriptor_;
  metadata.reflection = Treadmill_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Treadmill

// optional float distance = 1;
void Treadmill::clear_distance() {
  distance_ = 0;
}
 float Treadmill::distance() const {
  // @@protoc_insertion_point(field_get:Treadmill.distance)
  return distance_;
}
 void Treadmill::set_distance(float value) {
  
  distance_ = value;
  // @@protoc_insertion_point(field_set:Treadmill.distance)
}

// optional float avgSpeed = 2;
void Treadmill::clear_avgspeed() {
  avgspeed_ = 0;
}
 float Treadmill::avgspeed() const {
  // @@protoc_insertion_point(field_get:Treadmill.avgSpeed)
  return avgspeed_;
}
 void Treadmill::set_avgspeed(float value) {
  
  avgspeed_ = value;
  // @@protoc_insertion_point(field_set:Treadmill.avgSpeed)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int RowingMachine::kDurationFieldNumber;
const int RowingMachine::kRepsPerMinFieldNumber;
#endif  // !_MSC_VER

RowingMachine::RowingMachine()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:RowingMachine)
}

void RowingMachine::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

RowingMachine::RowingMachine(const RowingMachine& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:RowingMachine)
}

void RowingMachine::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  duration_ = 0;
  repspermin_ = 0;
}

RowingMachine::~RowingMachine() {
  // @@protoc_insertion_point(destructor:RowingMachine)
  SharedDtor();
}

void RowingMachine::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RowingMachine::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RowingMachine::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RowingMachine_descriptor_;
}

const RowingMachine& RowingMachine::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_EquipmentManager_2eproto();
  return *default_instance_;
}

RowingMachine* RowingMachine::default_instance_ = NULL;

RowingMachine* RowingMachine::New(::google::protobuf::Arena* arena) const {
  RowingMachine* n = new RowingMachine;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RowingMachine::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<RowingMachine*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(duration_, repspermin_);

#undef ZR_HELPER_
#undef ZR_

}

bool RowingMachine::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RowingMachine)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float duration = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &duration_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_repsPerMin;
        break;
      }

      // optional float repsPerMin = 2;
      case 2: {
        if (tag == 21) {
         parse_repsPerMin:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &repspermin_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RowingMachine)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RowingMachine)
  return false;
#undef DO_
}

void RowingMachine::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RowingMachine)
  // optional float duration = 1;
  if (this->duration() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->duration(), output);
  }

  // optional float repsPerMin = 2;
  if (this->repspermin() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->repspermin(), output);
  }

  // @@protoc_insertion_point(serialize_end:RowingMachine)
}

::google::protobuf::uint8* RowingMachine::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:RowingMachine)
  // optional float duration = 1;
  if (this->duration() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->duration(), target);
  }

  // optional float repsPerMin = 2;
  if (this->repspermin() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->repspermin(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:RowingMachine)
  return target;
}

int RowingMachine::ByteSize() const {
  int total_size = 0;

  // optional float duration = 1;
  if (this->duration() != 0) {
    total_size += 1 + 4;
  }

  // optional float repsPerMin = 2;
  if (this->repspermin() != 0) {
    total_size += 1 + 4;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RowingMachine::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const RowingMachine* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const RowingMachine>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RowingMachine::MergeFrom(const RowingMachine& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.duration() != 0) {
    set_duration(from.duration());
  }
  if (from.repspermin() != 0) {
    set_repspermin(from.repspermin());
  }
}

void RowingMachine::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RowingMachine::CopyFrom(const RowingMachine& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RowingMachine::IsInitialized() const {

  return true;
}

void RowingMachine::Swap(RowingMachine* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RowingMachine::InternalSwap(RowingMachine* other) {
  std::swap(duration_, other->duration_);
  std::swap(repspermin_, other->repspermin_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RowingMachine::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RowingMachine_descriptor_;
  metadata.reflection = RowingMachine_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RowingMachine

// optional float duration = 1;
void RowingMachine::clear_duration() {
  duration_ = 0;
}
 float RowingMachine::duration() const {
  // @@protoc_insertion_point(field_get:RowingMachine.duration)
  return duration_;
}
 void RowingMachine::set_duration(float value) {
  
  duration_ = value;
  // @@protoc_insertion_point(field_set:RowingMachine.duration)
}

// optional float repsPerMin = 2;
void RowingMachine::clear_repspermin() {
  repspermin_ = 0;
}
 float RowingMachine::repspermin() const {
  // @@protoc_insertion_point(field_get:RowingMachine.repsPerMin)
  return repspermin_;
}
 void RowingMachine::set_repspermin(float value) {
  
  repspermin_ = value;
  // @@protoc_insertion_point(field_set:RowingMachine.repsPerMin)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int Equipment::kNameFieldNumber;
const int Equipment::kDateFieldNumber;
const int Equipment::kTreadmillFieldNumber;
const int Equipment::kRowingMachineFieldNumber;
#endif  // !_MSC_VER

Equipment::Equipment()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Equipment)
}

void Equipment::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  Equipment_default_oneof_instance_->treadmill_ = const_cast< ::Treadmill*>(&::Treadmill::default_instance());
  Equipment_default_oneof_instance_->rowingmachine_ = const_cast< ::RowingMachine*>(&::RowingMachine::default_instance());
}

Equipment::Equipment(const Equipment& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Equipment)
}

void Equipment::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  date_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_EquipmentType();
}

Equipment::~Equipment() {
  // @@protoc_insertion_point(destructor:Equipment)
  SharedDtor();
}

void Equipment::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  date_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (has_EquipmentType()) {
    clear_EquipmentType();
  }
  if (this != default_instance_) {
  }
}

void Equipment::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Equipment::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Equipment_descriptor_;
}

const Equipment& Equipment::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_EquipmentManager_2eproto();
  return *default_instance_;
}

Equipment* Equipment::default_instance_ = NULL;

Equipment* Equipment::New(::google::protobuf::Arena* arena) const {
  Equipment* n = new Equipment;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Equipment::clear_EquipmentType() {
  switch(EquipmentType_case()) {
    case kTreadmill: {
      delete EquipmentType_.treadmill_;
      break;
    }
    case kRowingMachine: {
      delete EquipmentType_.rowingmachine_;
      break;
    }
    case EQUIPMENTTYPE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = EQUIPMENTTYPE_NOT_SET;
}


void Equipment::Clear() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  date_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_EquipmentType();
}

bool Equipment::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Equipment)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Equipment.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_date;
        break;
      }

      // optional string date = 2;
      case 2: {
        if (tag == 18) {
         parse_date:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_date()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->date().data(), this->date().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Equipment.date"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_treadmill;
        break;
      }

      // optional .Treadmill treadmill = 4;
      case 4: {
        if (tag == 34) {
         parse_treadmill:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_treadmill()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_rowingMachine;
        break;
      }

      // optional .RowingMachine rowingMachine = 5;
      case 5: {
        if (tag == 42) {
         parse_rowingMachine:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rowingmachine()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Equipment)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Equipment)
  return false;
#undef DO_
}

void Equipment::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Equipment)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Equipment.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional string date = 2;
  if (this->date().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->date().data(), this->date().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Equipment.date");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->date(), output);
  }

  // optional .Treadmill treadmill = 4;
  if (has_treadmill()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *EquipmentType_.treadmill_, output);
  }

  // optional .RowingMachine rowingMachine = 5;
  if (has_rowingmachine()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *EquipmentType_.rowingmachine_, output);
  }

  // @@protoc_insertion_point(serialize_end:Equipment)
}

::google::protobuf::uint8* Equipment::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Equipment)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Equipment.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional string date = 2;
  if (this->date().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->date().data(), this->date().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Equipment.date");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->date(), target);
  }

  // optional .Treadmill treadmill = 4;
  if (has_treadmill()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, *EquipmentType_.treadmill_, target);
  }

  // optional .RowingMachine rowingMachine = 5;
  if (has_rowingmachine()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, *EquipmentType_.rowingmachine_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Equipment)
  return target;
}

int Equipment::ByteSize() const {
  int total_size = 0;

  // optional string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional string date = 2;
  if (this->date().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->date());
  }

  switch (EquipmentType_case()) {
    // optional .Treadmill treadmill = 4;
    case kTreadmill: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *EquipmentType_.treadmill_);
      break;
    }
    // optional .RowingMachine rowingMachine = 5;
    case kRowingMachine: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *EquipmentType_.rowingmachine_);
      break;
    }
    case EQUIPMENTTYPE_NOT_SET: {
      break;
    }
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Equipment::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Equipment* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Equipment>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Equipment::MergeFrom(const Equipment& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  switch (from.EquipmentType_case()) {
    case kTreadmill: {
      mutable_treadmill()->::Treadmill::MergeFrom(from.treadmill());
      break;
    }
    case kRowingMachine: {
      mutable_rowingmachine()->::RowingMachine::MergeFrom(from.rowingmachine());
      break;
    }
    case EQUIPMENTTYPE_NOT_SET: {
      break;
    }
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.date().size() > 0) {

    date_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.date_);
  }
}

void Equipment::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Equipment::CopyFrom(const Equipment& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Equipment::IsInitialized() const {

  return true;
}

void Equipment::Swap(Equipment* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Equipment::InternalSwap(Equipment* other) {
  name_.Swap(&other->name_);
  date_.Swap(&other->date_);
  std::swap(EquipmentType_, other->EquipmentType_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Equipment::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Equipment_descriptor_;
  metadata.reflection = Equipment_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Equipment

// optional string name = 1;
void Equipment::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Equipment::name() const {
  // @@protoc_insertion_point(field_get:Equipment.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Equipment::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Equipment.name)
}
 void Equipment::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Equipment.name)
}
 void Equipment::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Equipment.name)
}
 ::std::string* Equipment::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Equipment.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Equipment::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Equipment::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Equipment.name)
}

// optional string date = 2;
void Equipment::clear_date() {
  date_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Equipment::date() const {
  // @@protoc_insertion_point(field_get:Equipment.date)
  return date_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Equipment::set_date(const ::std::string& value) {
  
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Equipment.date)
}
 void Equipment::set_date(const char* value) {
  
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Equipment.date)
}
 void Equipment::set_date(const char* value, size_t size) {
  
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Equipment.date)
}
 ::std::string* Equipment::mutable_date() {
  
  // @@protoc_insertion_point(field_mutable:Equipment.date)
  return date_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Equipment::release_date() {
  
  return date_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Equipment::set_allocated_date(::std::string* date) {
  if (date != NULL) {
    
  } else {
    
  }
  date_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), date);
  // @@protoc_insertion_point(field_set_allocated:Equipment.date)
}

// optional .Treadmill treadmill = 4;
bool Equipment::has_treadmill() const {
  return EquipmentType_case() == kTreadmill;
}
void Equipment::set_has_treadmill() {
  _oneof_case_[0] = kTreadmill;
}
void Equipment::clear_treadmill() {
  if (has_treadmill()) {
    delete EquipmentType_.treadmill_;
    clear_has_EquipmentType();
  }
}
 const ::Treadmill& Equipment::treadmill() const {
  // @@protoc_insertion_point(field_get:Equipment.treadmill)
  return has_treadmill()
      ? *EquipmentType_.treadmill_
      : ::Treadmill::default_instance();
}
::Treadmill* Equipment::mutable_treadmill() {
  if (!has_treadmill()) {
    clear_EquipmentType();
    set_has_treadmill();
    EquipmentType_.treadmill_ = new ::Treadmill;
  }
  // @@protoc_insertion_point(field_mutable:Equipment.treadmill)
  return EquipmentType_.treadmill_;
}
::Treadmill* Equipment::release_treadmill() {
  if (has_treadmill()) {
    clear_has_EquipmentType();
    ::Treadmill* temp = EquipmentType_.treadmill_;
    EquipmentType_.treadmill_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void Equipment::set_allocated_treadmill(::Treadmill* treadmill) {
  clear_EquipmentType();
  if (treadmill) {
    set_has_treadmill();
    EquipmentType_.treadmill_ = treadmill;
  }
  // @@protoc_insertion_point(field_set_allocated:Equipment.treadmill)
}

// optional .RowingMachine rowingMachine = 5;
bool Equipment::has_rowingmachine() const {
  return EquipmentType_case() == kRowingMachine;
}
void Equipment::set_has_rowingmachine() {
  _oneof_case_[0] = kRowingMachine;
}
void Equipment::clear_rowingmachine() {
  if (has_rowingmachine()) {
    delete EquipmentType_.rowingmachine_;
    clear_has_EquipmentType();
  }
}
 const ::RowingMachine& Equipment::rowingmachine() const {
  // @@protoc_insertion_point(field_get:Equipment.rowingMachine)
  return has_rowingmachine()
      ? *EquipmentType_.rowingmachine_
      : ::RowingMachine::default_instance();
}
::RowingMachine* Equipment::mutable_rowingmachine() {
  if (!has_rowingmachine()) {
    clear_EquipmentType();
    set_has_rowingmachine();
    EquipmentType_.rowingmachine_ = new ::RowingMachine;
  }
  // @@protoc_insertion_point(field_mutable:Equipment.rowingMachine)
  return EquipmentType_.rowingmachine_;
}
::RowingMachine* Equipment::release_rowingmachine() {
  if (has_rowingmachine()) {
    clear_has_EquipmentType();
    ::RowingMachine* temp = EquipmentType_.rowingmachine_;
    EquipmentType_.rowingmachine_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void Equipment::set_allocated_rowingmachine(::RowingMachine* rowingmachine) {
  clear_EquipmentType();
  if (rowingmachine) {
    set_has_rowingmachine();
    EquipmentType_.rowingmachine_ = rowingmachine;
  }
  // @@protoc_insertion_point(field_set_allocated:Equipment.rowingMachine)
}

bool Equipment::has_EquipmentType() const {
  return EquipmentType_case() != EQUIPMENTTYPE_NOT_SET;
}
void Equipment::clear_has_EquipmentType() {
  _oneof_case_[0] = EQUIPMENTTYPE_NOT_SET;
}
Equipment::EquipmentTypeCase Equipment::EquipmentType_case() const {
  return Equipment::EquipmentTypeCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int EquipmentCache::kEquipmentFieldNumber;
#endif  // !_MSC_VER

EquipmentCache::EquipmentCache()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:EquipmentCache)
}

void EquipmentCache::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

EquipmentCache::EquipmentCache(const EquipmentCache& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:EquipmentCache)
}

void EquipmentCache::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

EquipmentCache::~EquipmentCache() {
  // @@protoc_insertion_point(destructor:EquipmentCache)
  SharedDtor();
}

void EquipmentCache::SharedDtor() {
  if (this != default_instance_) {
  }
}

void EquipmentCache::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EquipmentCache::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EquipmentCache_descriptor_;
}

const EquipmentCache& EquipmentCache::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_EquipmentManager_2eproto();
  return *default_instance_;
}

EquipmentCache* EquipmentCache::default_instance_ = NULL;

EquipmentCache* EquipmentCache::New(::google::protobuf::Arena* arena) const {
  EquipmentCache* n = new EquipmentCache;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void EquipmentCache::Clear() {
  equipment_.Clear();
}

bool EquipmentCache::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:EquipmentCache)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Equipment equipment = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_equipment:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_equipment()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_equipment;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:EquipmentCache)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:EquipmentCache)
  return false;
#undef DO_
}

void EquipmentCache::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:EquipmentCache)
  // repeated .Equipment equipment = 1;
  for (unsigned int i = 0, n = this->equipment_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->equipment(i), output);
  }

  // @@protoc_insertion_point(serialize_end:EquipmentCache)
}

::google::protobuf::uint8* EquipmentCache::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:EquipmentCache)
  // repeated .Equipment equipment = 1;
  for (unsigned int i = 0, n = this->equipment_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->equipment(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:EquipmentCache)
  return target;
}

int EquipmentCache::ByteSize() const {
  int total_size = 0;

  // repeated .Equipment equipment = 1;
  total_size += 1 * this->equipment_size();
  for (int i = 0; i < this->equipment_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->equipment(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EquipmentCache::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const EquipmentCache* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const EquipmentCache>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void EquipmentCache::MergeFrom(const EquipmentCache& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  equipment_.MergeFrom(from.equipment_);
}

void EquipmentCache::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EquipmentCache::CopyFrom(const EquipmentCache& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EquipmentCache::IsInitialized() const {

  return true;
}

void EquipmentCache::Swap(EquipmentCache* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EquipmentCache::InternalSwap(EquipmentCache* other) {
  equipment_.UnsafeArenaSwap(&other->equipment_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata EquipmentCache::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = EquipmentCache_descriptor_;
  metadata.reflection = EquipmentCache_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// EquipmentCache

// repeated .Equipment equipment = 1;
int EquipmentCache::equipment_size() const {
  return equipment_.size();
}
void EquipmentCache::clear_equipment() {
  equipment_.Clear();
}
const ::Equipment& EquipmentCache::equipment(int index) const {
  // @@protoc_insertion_point(field_get:EquipmentCache.equipment)
  return equipment_.Get(index);
}
::Equipment* EquipmentCache::mutable_equipment(int index) {
  // @@protoc_insertion_point(field_mutable:EquipmentCache.equipment)
  return equipment_.Mutable(index);
}
::Equipment* EquipmentCache::add_equipment() {
  // @@protoc_insertion_point(field_add:EquipmentCache.equipment)
  return equipment_.Add();
}
::google::protobuf::RepeatedPtrField< ::Equipment >*
EquipmentCache::mutable_equipment() {
  // @@protoc_insertion_point(field_mutable_list:EquipmentCache.equipment)
  return &equipment_;
}
const ::google::protobuf::RepeatedPtrField< ::Equipment >&
EquipmentCache::equipment() const {
  // @@protoc_insertion_point(field_list:EquipmentCache.equipment)
  return equipment_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
